repeat_types:
  week: "Weekly"
  month: "Monthly"
date_format: "%d/%m/%Y"
time_format: "%H:%M"
hour_begin_schedule: 7
hour_end_schedule: 22
per_page: 2
user_roles:
  admin: "admin"
  normal: "normal"
number_of_schedules: 8
avatar: [150, 150]
max_avatar_file_size: 5
avatar_extension_white_list: ["jpg", "jpeg", "gif", "png"]
rooms:
  - name: "Australia 1"
    color: "#D87093"
  - name: "Australia 2"
    color: "#20BA22a"
  - name: "Pacific"
    color: "#008080"
  - name: "Atlatic"
    color: "#456321"
options:
  - "Calendar"
  - "Refresh"
